viewer: prevent crash when headers are nil
Prevent the following error from happening:

Error: runtime error: invalid memory address or nil pointer dereference

panic({0x11206c0?, 0x18dd700?})
	runtime/panic.go:792 +0x132
git.sr.ht/~rjarry/aerc/lib/auth.New.CreateParser.func1(0x0, {0x0, 0x0, 0x0})
	                                               ^^^
	git.sr.ht/~rjarry/aerc/lib/auth/auth.go:77 +0xdb
git.sr.ht/~rjarry/aerc/app.NewMessageViewer.func2(...)
	git.sr.ht/~rjarry/aerc/app/msgviewer.go:93 +0x517
git.sr.ht/~rjarry/aerc/app.HeaderLayout.grid(...)
	git.sr.ht/~rjarry/aerc/app/headerlayout.go:39 +0x19e
git.sr.ht/~rjarry/aerc/app.NewMessageViewer(...)
	git.sr.ht/~rjarry/aerc/app/msgviewer.go:72 +0x185
git.sr.ht/~rjarry/aerc/commands/account.ViewMessage.Execute.func1(...)
	git.sr.ht/~rjarry/aerc/commands/account/view.go:68 +0x95
git.sr.ht/~rjarry/aerc/lib.NewMessageStoreView.func1(...)
	git.sr.ht/~rjarry/aerc/lib/messageview.go:80
git.sr.ht/~rjarry/aerc/lib.NewMessageStoreView(...)
	git.sr.ht/~rjarry/aerc/lib/messageview.go:127 +0x3e5
git.sr.ht/~rjarry/aerc/commands/account.ViewMessage.Execute(...)
	git.sr.ht/~rjarry/aerc/commands/account/view.go:57 +0x3c5
git.sr.ht/~rjarry/aerc/commands.ExecuteCommand(...)
	git.sr.ht/~rjarry/aerc/commands/commands.go:218 +0x73d
main.execCommand(...)
	git.sr.ht/~rjarry/aerc/main.go:45 +0x69
git.sr.ht/~rjarry/aerc/app.(*Aerc).BeginExCommand.func1(...)
	git.sr.ht/~rjarry/aerc/app/aerc.go:645 +0x5e
git.sr.ht/~rjarry/aerc/app.(*ExLine).Event(...)
	git.sr.ht/~rjarry/aerc/app/exline.go:92 +0xb82
git.sr.ht/~rjarry/aerc/app.(*Aerc).Event(...)
	git.sr.ht/~rjarry/aerc/app/aerc.go:344 +0x87e
git.sr.ht/~rjarry/aerc/app.(*Aerc).simulate(...)
	git.sr.ht/~rjarry/aerc/app/aerc.go:315 +0x2ae
git.sr.ht/~rjarry/aerc/app.(*Aerc).Event(...)
	git.sr.ht/~rjarry/aerc/app/aerc.go:377 +0xc45
git.sr.ht/~rjarry/aerc/lib/ui.HandleEvent(...)
	git.sr.ht/~rjarry/aerc/lib/ui/ui.go:188 +0x5e9
main.main()
	git.sr.ht/~rjarry/aerc/main.go:298 +0x11b4

Do not try to build an auth header set if the message headers are nil.

Reported-by: Moritz Poldrack <moritz@poldrack.dev>
Signed-off-by: Robin Jarry <robin@jarry.cc>
Reviewed-by: Simon Martin <simon@nasilyan.com>