mod: remove support for go 1.16
The dependency to x/tools@v0.6.0 drags x/sys@v0.5.0 which is not
compatible with go 1.16

 # golang.org/x/sys/unix
 golang.org/x/sys@v0.5.0/unix/syscall.go:83:16: undefined: unsafe.Slice
 golang.org/x/sys@v0.5.0/unix/syscall_linux.go:2271:9: undefined: unsafe.Slice
 golang.org/x/sys@v0.5.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
 golang.org/x/sys@v0.5.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
 note: module requires Go 1.17

Since go 1.16 is now EOL, update the minimal go version to 1.17.

Update go.mod and go.sum with the following command:

 go mod tidy -compat=1.17

Signed-off-by: Robin Jarry <robin@jarry.cc>
Acked-by: Moritz Poldrack <moritz@poldrack.dev>