config: fix error when temporary-directory is not set
Fix the following error on startup:

 error: ~/.config/aerc/aerc.conf: [general].temporary-directory:
   stat "": no such file or directory

When the setting is empty, use the platform default temp directory.

Fixes: 05ec40d81d02 ("config: allow specifying the temporary directory")
Reported-by: Jon Fineman <jon@fineman.me>
Reported-by: Julio B <julio.bacel@gmail.com>
Signed-off-by: Robin Jarry <robin@jarry.cc>
Reviewed-by: Tristan Partin <tristan@partin.io>