ci: fix ancient go package url
Alpine 3.19 repository does not have go 1.22. Only Alpine 3.20 has.

+ curl -O https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/go-1.22.10-r0.apk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   153  100   153    0     0   4380      0 --:--:-- --:--:-- --:--:--  4500
+ sudo apk add ./go-1.22.10-r0.apk
ERROR: ./go-1.22.10-r0.apk: IO ERROR

Fix the URL and add the -f (--fail) and -L (--location) flags to support
any redirects and report explicit errors instead of silently downloading
a 404 HTML page and letting `apk add` fail with an obscure error.

For the record, here is the error with curl -f:

+ curl -fOL https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/go-1.22.10-r0.apk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

Fixes: 5f97f73622e1 ("ci: update dependencies to fix go 1.24 failures")
Signed-off-by: Robin Jarry <robin@jarry.cc>